apiVersion: v1
kind: Service
metadata:
  name: {{ include "acronis-exporter.fullname" . }}
  labels:
    {{- include "acronis-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9666
      protocol: TCP
      name: acronis-exporter
  selector:
    {{- include "acronis-exporter.selectorLabels" . | nindent 4 }}
