apiVersion: v2
name: acronis-policy-exporter
type: application
version: 0.0.1
appVersion: 0.0.1
description: Prometheus monitoring of Acronis tasks and policy state
home: https://github.com/liquidweb/acronis-policy-exporter
sources:
  - https://github.com/liquidweb/acronis-policy-exporter
