name: commit jobs

on:
  push:
    branches: [ main ]


jobs:
  go-test:
    runs-on: ubuntu-latest
    container:
      image: golang:alpine
      options: --cpus 1
    steps:
    - uses: actions/checkout@master
    - name: non-interactive go test
      run: go test -v ./...
      env:
        CGO_ENABLED: 0


  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: docker.pkg.github.com
          password: ${{ secrets.GITHUB_TOKEN }}
          image: acronis-policy-exporter
          cache: false

  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Helm Lint
        run: helm lint charts/acronis-policy-exporter

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
