name: commit jobs

on:
  push:
    branches: [ main ]


jobs:
  go-test:
    runs-on: ubuntu-latest
    container:
      image: golang:alpine
      options: --cpus 1
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: non-interactive go test
      run: go test -v ./...

  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: docker.pkg.github.com
          password: ${{ secrets.GITHUB_TOKEN }}
          image: acronis-policy-exporter
          cache: true
          cache_registry: acronis-policy-exporter-cache