name: commit jobs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  go-test:
    runs-on: ubuntu-latest
    container:
      image: golang:alpine
      options: --cpus 1
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: non-interactive go test
      run: go test -v ./...